services:
  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      app_net:
        ipv4_address: 172.31.240.10

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.240.0/24
